language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
branches:
  only:
    - master
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
notifications:
  email:
    on_success: never
    on_failure: always